---
title: "Coronavirus"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    vertical_layout: fill
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
#------------------ Packages ------------------
library(flexdashboard)
library(plotly)


`%>%` <- magrittr::`%>%`
#------------------ Parameters ------------------
# Set colors
# https://www.w3.org/TR/css-color-3/#svg-color
confirmed_color <- "purple"
active_color <- "#1f77b4"
recovered_color <- "forestgreen"
death_color <- "red"
#------------------ Data ------------------
data<-read.csv("https://raw.githubusercontent.com/GhoraiVanga/Covid19/master/Covid19.csv")

df <- data %>% 
     dplyr::select(State ,Confirmed,Recovered,Deaths,Active)

 Data1<- read.csv("https://raw.githubusercontent.com/GhoraiVanga/Covid19/master/Time_Wise_Data.csv")
 Data1$Date=as.Date(Data1$Date, "%d-%b")

  
#------------trajectory plot data prep------------





```

Summary
=======================================================================
Row
-----------------------------------------------------------------------

### confirmed {.value-box}

```{r}

valueBox(value = paste(format(sum(df$Confirmed), big.mark = ","), "", sep = " "), 
         caption = "Total Confirmed Cases", 
         icon = "fas fa-user-md", 
         color = confirmed_color)
```


### active {.value-box}

```{r}
valueBox(value = paste(format(sum(df$Active, na.rm = TRUE), big.mark = ","), " (",
                       round(100 * sum(df$Active, na.rm = TRUE) / sum(df$Confirmed), 1), 
                       "%)", sep = ""), 
         caption = "Active Cases", icon = "fas fa-ambulance", 
         color = active_color)
```

### recovered {.value-box}

```{r}
valueBox(value = paste(format(sum(df$Recovered, na.rm = TRUE), big.mark = ","), " (",
                       round(100 * sum(df$Recovered, na.rm = TRUE) / sum(df$Active), 1), 
                       "%)", sep = ""), 
         caption = "Recovered Cases", icon = "fas fa-heartbeat", 
         color = recovered_color)
```

### death {.value-box}

```{r}

valueBox(value = paste(format(sum(df$Deaths, na.rm = TRUE), big.mark = ","), " (",
                       round(100 * sum(df$Deaths, na.rm = TRUE) / sum(df$Confirmed), 1), 
                       "%)", sep = ""),
         caption = "Death Cases", 
         icon = "fas fa-heart-broken", 
         color = death_color)
```


Row
-----------------------------------------------------------------------

### Cases Distribution by State

```{r daily_summary}


p=plotly::plot_ly(df ,
                x =df$State  , 
                y = df$Active, 
                # text =  ~ confirmed, 
                # textposition = 'auto',
                type = "bar", 
                name = "Active",
                marker = list(color = active_color)) %>%
  plotly::add_trace(y = df$Recovered, 
                    # text =  ~ recovered, 
                    # textposition = 'auto',
                    name = "Recovered",
                    marker = list(color = recovered_color)) %>%
  plotly::add_trace(y = df$Deaths, 
                    # text =  ~ death, 
                    # textposition = 'auto',
                    name = "Death",
                    marker = list(color = death_color)) %>%
  plotly::layout(barmode = 'stack',
                 yaxis = list(title = "Total Cases (log scaled)",
                              type = "log"),
                 xaxis = list(title = "",categoryorder = "array",
                              categoryarray=df$State),
                 
                 hovermode = "compare",
                 margin =  list(
                   # l = 60,
                   # r = 40,
                   b = 60,
                   t = 40,
                   pad = 2
                 ))

ggplotly(p) %>% config(displayModeBar = F) %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))



  


```

Row {data-width=400}
-----------------------------------------------------------------------


### Daily Cumulative Cases by Type
    
```{r}

# plotly::plot_ly(df_daily, x = ~date, y = ~active_cum, name = 'Active', type = 'scatter', mode = 'none', stackgroup = 'one', fillcolor = "#1f77b4") %>%
# plotly::add_trace(y = ~recovered_cum, name = 'Recovered', fillcolor = "green") %>%
# plotly::add_trace(y = ~death_cum, name = "Death", fillcolor = "red") %>%
#   plotly::layout(title = "",
#          xaxis = list(title = "",
#                       showgrid = FALSE),
#          yaxis = list(title = "Cumulative Number of Cases",
#                       showgrid = FALSE),
#          legend = list(x = 0.1, y = 0.9),
#                  hovermode = "compare")


q=plotly::plot_ly(data = Data1,
                x = ~ Date,
                y = ~ Total.Confirmed, 
                name = 'Active', 
                fillcolor = active_color,
                type = 'scatter',
                mode = 'none', 
                stackgroup = 'one') %>%
  plotly::add_trace(y = ~ Total.Recovered,
                    name = "Recovered",
                    fillcolor = recovered_color) %>%
  plotly::add_trace(y = ~ Total.Deceased,
                    name = "Death",
                    fillcolor = death_color) %>%
  plotly::layout(title = "",
                 yaxis = list(title = "Cumulative Number of Cases"),
                 xaxis = list(title = "Date"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")
ggplotly(q) %>% config(displayModeBar = F) %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
  

```


### Recovery and Death Rates by State
    
```{r}
df_summary <-df %>%
  dplyr::mutate(recover_rate = Recovered / Confirmed,
                death_rate = Deaths / Confirmed)  
df_summary %>%
  DT::datatable(
            options = list(pageLength = nrow(df_summary), dom = 'tip')) %>%
  DT::formatPercentage("recover_rate", 2) %>%
  DT::formatPercentage("death_rate", 2)  
```


Map
=======================================================================

**COMMING SOON**

```{r}

```

Trends
=======================================================================

**COMING SOON**

Column {data-width=400}
-------------------------------------
    

    
```{r}


```




```{r}

```
   
Column {data-width=600}
-------------------------------------
   


```{r}

  
```   
 

    
```{r}

```

Data
=======================================================================

```{r}

```



About Me
=======================================================================

**About Me**
Name-Suman Ghorai
[Linkdln](www.linkedin.com/in/suman-ghorai-397357b7)
Email-ghorai77@gmail.com




